DROP TABLE Appointments;
DROP TABLE Vehicles;
DROP TABLE Qualifications;
DROP TABLE Users;
DROP TABLE Fields;
DROP TABLE Roles;

CREATE TABLE Roles (
	role_id NUMBER(10) GENERATED by default on null as IDENTITY,
	role_name VARCHAR2(255) NOT NULL,
	CONSTRAINT roles_pk PRIMARY KEY (role_id)
);

CREATE TABLE Fields (
	field_id NUMBER(10) GENERATED by default on null as IDENTITY,
	field_name VARCHAR2(255) NOT NULL,
	CONSTRAINT fields_pk PRIMARY KEY (field_id)
);

CREATE TABLE Users (
	user_id NUMBER(10) GENERATED by default on null as IDENTITY,
	first_name VARCHAR2(255) NOT NULL,
	last_name VARCHAR2(255) NOT NULL,
	phone_number VARCHAR2(255) UNIQUE NOT NULL,
	username VARCHAR2(255) UNIQUE NOT NULL,
	password VARCHAR2(255) NOT NULL,
	role_id NUMBER(10) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (user_id),
	CONSTRAINT fk_users FOREIGN KEY (role_id) REFERENCES Roles(role_id)
);

CREATE TABLE Qualifications (
	qualification_id NUMBER(10) GENERATED by default on null as IDENTITY,
	user_id NUMBER(10) NOT NULL,
	field_id NUMBER(10) NOT NULL,
	CONSTRAINT qualifications_pk PRIMARY KEY (qualification_id),
	CONSTRAINT fk_qualifications_users FOREIGN KEY (user_id) REFERENCES Users(user_id),
	CONSTRAINT fk_qualifications_fields FOREIGN KEY (field_id) REFERENCES Fields(field_id)
);

CREATE TABLE Vehicles (
	vehicle_id NUMBER(10) GENERATED by default on null as IDENTITY,
	vehicle_plate VARCHAR2(8) UNIQUE NOT NULL,
	vehicle_make VARCHAR2(255) NOT NULL,
	vehicle_model VARCHAR2(255) NOT NULL,
	user_id NUMBER(10) NOT NULL,
	CONSTRAINT vehicles_pk PRIMARY KEY (vehicle_id),
	CONSTRAINT fk_vehicles FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

CREATE TABLE Appointments (
	appointment_id NUMBER(10) GENERATED by default on null as IDENTITY,
	appointment_date VARCHAR2(255) NOT NULL,
	vehicle_id NUMBER(10) NOT NULL,
	user_id NUMBER(10) NOT NULL,
	appointment_approved NUMBER(10) NOT NULL,
	appointment_status VARCHAR2(10) NOT NULL,
	CONSTRAINT appointments_pk PRIMARY KEY (appointment_id),
	CONSTRAINT fk_appointments_vehicles FOREIGN KEY (vehicle_id) REFERENCES Vehicles(vehicle_id),
	CONSTRAINT fk_appointments_users FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

INSERT INTO Roles(role_name) VALUES('Admin');
INSERT INTO Roles(role_name) VALUES('Technician');
INSERT INTO Roles(role_name) VALUES('Client');
INSERT INTO Roles(role_name) VALUES('Analyst');